### ISSUE TITLE
[1.19.2] Dedicated server crash at start-up

### ISSUE THREAD

**Issue by kwpugh** [Marwinkas/MysticalCrops#1]
crash report: https://gist.github.com/kwpugh/c1b176793902e4a825cbda9f3a2d6873

fabric:   fabric-server-1.19.2-0.14.9.jar
mod: mysticalcrops-1.1.0-1.19.2.jar

**Comment by Marwinkas** [comment]
Fixed in 1.1.1 . Thanks for issue.
