### ISSUE TITLE
Gui's are slightly misaligned

### ISSUE THREAD

**Issue by bdani0717** [Marwinkas/MysticalCrops#10]
The gui of botanic table, infusion table and ritual table are 1-2 pixels off from the inventory slots (or the inventory slots are not positioned correctly). This is especialy visible if you change the window size. Also the gui of the ritual table is stretched verticaly due to the texture being 274x256 instead of 256x256
![ritualtable](https://user-images.githubusercontent.com/26284661/200186775-362456e0-a456-4b17-8d3d-55b0fc829563.png)
![infusiontable](https://user-images.githubusercontent.com/26284661/200186777-b9687a8d-d1fd-463d-a72f-c5415b97e1ef.png)
![botanictable](https://user-images.githubusercontent.com/26284661/200186778-f6b0159a-98b2-4b37-b153-a97362a47501.png)

**Comment by Marwinkas** [comment]
Thanks for issue! Fixed! I'm sorry I didn't fix it for a long time. I currently have very little time to develop a mod
