### ISSUE TITLE
Hoppers input essence into output slot of infusion table

### ISSUE THREAD

**Issue by alcatrazSyndr** [Marwinkas/MysticalCrops#15]
When trying to automate the essence creation

When having a hopper input common essence into the infusion table, once the 4 input slots get filled up, the hopper keeps inputting common essence into the output slot, causing the automation of essence fusing being unviable

**Comment by Marwinkas** [comment]
Thanks for issue! Fixed and you can automate infusion, ritual and botanical table! I'm sorry I didn't fix it for a long time. I currently have very little time to develop a mod
