### ISSUE TITLE
stone_plate recipe conflict

### ISSUE THREAD

**Issue by troyheady2** [Marwinkas/MysticalCrops#16]
The stone plate is conflicting with stone bricks. 

can you chance it up a bit. maybe a cross pattern of stone or add  smooth stone around the outside

**Comment by Marwinkas** [comment]
Thanks for issue! I will fix this in the next update, you can use cobblestone for crafting.

**Comment by Marwinkas** [comment]
Thanks for issue! Fixed in 1.7.6!
