### ISSUE TITLE
Recipe Conflicts & Other

### ISSUE THREAD

**Issue by cool-destiny** [Marwinkas/MysticalCrops#18]
In addition to issue #16, the following recipes conflict

sand_plate | sandstone
wood_plate | wood
echo_shard | sculk
weeping_vines | crimson_nylium
twisting_vines | warped_nylium

Other
Log excerpts
https://paste.ee/p/uSVUY

**Comment by Marwinkas** [comment]
Thanks for issue! Fixed in 1.7.6!
