### ISSUE TITLE
anvil interaction

### ISSUE THREAD

**Issue by troyheady2** [Marwinkas/MysticalCrops#19]
thank you for the other fix and for writing and maintaining such a cool mod.
I like this better that a lot of mining :)

i figured the perfect crystal would have a much higher durability.
I am still early game and low on diamonds....

I tried to repair the crystal in an anvil, but client (not server) crashed when I added the essence to the anvil 

I also tried unbreaking enchanted book, same thing. the client crashes when you add the book tot he anvil

again...sorry if i am causing trouble.

Thank you again!

**Comment by troyheady2** [comment]
crash report is it helps
https://pastebin.com/SB7tLKhe

**Comment by Marwinkas** [comment]
> In mod was not thought of repairing crystals, because game crashes. I might just increase the durability of the first levels of crystals. In the old versions, you could get many essence. 1 chest in 1 hour. In last version i decreased all things of get essence. Maybe crystals need more. I'll think about it and maybe in a week I'll change it

**Comment by Marwinkas** [comment]
Fixed in Mystical Nature 1.7.7. You can repair tool and crystal

**Comment by troyheady2** [comment]
thank you!  I will try not to bug you for a couple of months at least :)

**Comment by Marwinkas** [comment]
> 

If you find a bug, write issue :)
