### ISSUE TITLE
Cannot open GUI

### ISSUE THREAD

**Issue by JackBMX637** [Marwinkas/MysticalCrops#20]
On my server every time i try to open any table it gives me this error code in the console
Trying to open unregistered screen handler net.marwinka.mysticalcrops.screen.InfusionTableScreenHandler@a04b2ee
On the server it worked for a day following being updated before it stopped working.
it does the same thing with the botanical, ritual, and infusion tables.
the numbers following @ change each time I right click. this issue does not occur when playing in singleplayer.

**Comment by Marwinkas** [comment]
Version minecraft?

**Comment by JackBMX637** [comment]
1.19.2

**Comment by Marwinkas** [comment]
Fixed in Mystical Nature 1.7.7
