### ISSUE TITLE
[Suggestion] Higher tier essence plants should produce higher tier essence fruit

### ISSUE THREAD

**Issue by VaelophisNyx** [Marwinkas/MysticalCrops#24]
as is upgrading your plants is a theoretical time saver, but due to #23 it winds up being a time consumer anyway
it'd be nice if you could be better rewarded for upgrading your plants in general. I don't particularly care if I get more essence, if I am just upgrading that anyway

**Comment by Marwinkas** [comment]
Thanks, I'll think about it
