### ISSUE TITLE
Where can I download versions after 1.1.0?

### ISSUE THREAD

**Issue by Jade-TheCat** [Marwinkas/MysticalCrops#25]
Hello, I am looking to be able to play with this mod, but I am running into a bug that was supposedly fixed in 1.1.1. Modrinth only has up to 1.1.0, and I do not see the mod on CurseForge. It looks like there's a version of 1.8 released now. Is there somewhere I can download this without building it myself?

**Comment by Marwinkas** [comment]
https://www.curseforge.com/minecraft/mc-mods/mystical-nature. Mod renamed
