### ISSUE TITLE
push / pull issue with infusion tables

### ISSUE THREAD

**Issue by troyheady2** [Marwinkas/MysticalCrops#27]
I promised not to bug you ( [anvil interaction #19](https://github.com/Marwinkas/MysticalCrops/issues/19) ) for a couple of months :) 

i recently upgraded to current version ( mysticalnature-1.8-1.19.2.jar] )
Feb 8, 2023) on curseforge  ( https://www.curseforge.com/minecraft/mc-mods/mystical-nature/files/4388338 )

I am having trouble with feeding items to the infusion table, pipes and hoppers are not working.
also when the infusion table "processes" items they are "overwriting" the new created essence and not stacking.
.i.e.  put a stack of essence in each of the four slots and when done you only have one essence in the middle.
Hopper on the bottom will prevent this and will still pull the items out before they are overwritten

Thank you again for looking into this.
Let me know if you need more information

**Comment by Marwinkas** [comment]
I check infusion table tomorrow. With hopper i fix problem. But i need redraw crops for publish version, but i sick today and lay with temperature
 Sorry for waiting. When temperature set is normal, i publish new version in next day ;)

**Comment by troyheady2** [comment]
lol... it is only a mod!  

Take care of yourself and your health and don't push it.
catch you when you are better  :)

Get Well Soon!

**Comment by Marwinkas** [comment]
> Thanks,
A lot of people are already waiting for these bugs to be fixed and, but the update has not been released a lot of times. Now that I've sorted out the mod, the bugs fixes will be quick. And thank you for writing the issue, since you are the only one who wrote the problem with the infusion table. If you find something bugs write please, you really help mod
