### ISSUE TITLE
Recipes using Botanical and Ritual Tables not functioning in REI on multiplayer server

### ISSUE THREAD

**Issue by Zacknac** [Marwinkas/MysticalCrops#3]
Confirmed using only REI and Mystical Crops (and dependencies)
Works perfectly fine on singleplayer, not on a server.
Error stacktrace:
https://pastebin.com/7wr3BD9a

Love the mod by the way :D
![image](https://user-images.githubusercontent.com/77754097/191104476-bb414d05-32ab-4a89-9994-05ff49376754.png)

**Comment by Zacknac** [comment]
I have little experience with Java, so I might be full of hot air here, but it appears that in the categories file, you are only taking into account it running on the client, so when it tries to fetch the data from the server, it also tries to render on the server and errors out.

**Comment by Marwinkas** [comment]
> I have little experience with Java, so I might be full of hot air here, but I'll give my two cents. It appears that in the categories file, you are only taking into account it running on the client. So when it tries to fetch the data from the server, it also tries to render on the server and errors out.

Thanks for issue! I'm new to java and creating mods. This is my first mod that I created. I've been trying to fix this for more than 9 hours and it doesn't work :(. In the evening I will release fix: when using tables in multiplayer. I will fix this error in the next updates

**Comment by Marwinkas** [comment]
Thanks for issue! Sorry for such a long wait. Fixed in v1.6-1.19.2: https://www.curseforge.com/minecraft/mc-mods/mystical-nature/files/4052909
