### ISSUE TITLE
Disconnects from server when attempting to use Botanical Table

### ISSUE THREAD

**Issue by Zacknac** [Marwinkas/MysticalCrops#4]
![image](https://user-images.githubusercontent.com/77754097/191151639-5f2eaad2-1622-4867-a339-8332712fe2d2.png)
Crash disconnects when attempting to use the Botanical Table in a server (I assume the ritual table as well but I am yet to test it)
Does not crash in singleplayer.
Likely for the same reason that recipes don't work on REI when playing multiplayer.
Error log from server:
https://pastebin.com/vVjreMdD

**Comment by Zacknac** [comment]
#3 likely has the same cause

**Comment by Marwinkas** [comment]
Fixed in 1.4 1.19.2
